import { defineConfig, devices } from '@playwright/test';
import path from 'path';

/**
 * Valiant Law Portal — Playwright E2E Configuration
 *
 * Runs against: client (localhost:5173) backed by server (localhost:3000)
 * Browsers: Chromium, Firefox, WebKit
 *
 * Fixes applied:
 *   A2 — workers: undefined allows parallel execution; storageState reuse eliminates port-conflict concerns
 *   A3 — webServer timeout raised to 120 s for cold TypeScript / Vite starts
 *   A4 — webServer commands use --prefix so they work on both Windows (cmd) and Unix
 *   A5 — globalTeardown wired up for DB cleanup after the suite
 *   A6 — per-project storageState files (generated by globalSetup) reuse auth sessions
 */
export default defineConfig({
    globalSetup:    require.resolve('./e2e/global.setup'),
    globalTeardown: require.resolve('./e2e/global.teardown'),
    testDir: './e2e',
    fullyParallel: true,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: process.env.CI ? 2 : undefined,
    reporter: [
        ['html', { outputFolder: 'playwright-report' }],
        ['list'],
        ['json', { outputFile: 'e2e-errors.json' }],
    ],
    use: {
        baseURL:    'http://localhost:5173',
        trace:      'on-first-retry',
        screenshot: 'only-on-failure',
        video:      'on-first-retry',
    },
    projects: [
        // ── Browser projects ─────────────────────────────────────────────────
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
                // A6: reuse pre-authenticated client session; generated in globalSetup
                storageState: path.join(__dirname, 'e2e/.auth/client.json'),
            },
            testIgnore: ['**/global.setup.ts', '**/global.teardown.ts'],
        },
        {
            name: 'firefox',
            use: {
                ...devices['Desktop Firefox'],
                storageState: path.join(__dirname, 'e2e/.auth/client.json'),
            },
            testIgnore: ['**/global.setup.ts', '**/global.teardown.ts'],
        },
        {
            name: 'webkit',
            use: {
                ...devices['Desktop Safari'],
                storageState: path.join(__dirname, 'e2e/.auth/client.json'),
            },
            testIgnore: ['**/global.setup.ts', '**/global.teardown.ts'],
        },
        // ── Lawyer project (separate auth state) ─────────────────────────────
        {
            name: 'chromium-lawyer',
            use: {
                ...devices['Desktop Chrome'],
                storageState: path.join(__dirname, 'e2e/.auth/lawyer.json'),
            },
            testMatch: ['**/lawyer-review.spec.ts', '**/nudge-email.spec.ts'],
        },
    ],
    webServer: [
        {
            // A4: use --prefix instead of `cd server &&` for Windows/Unix compat
            command: 'npm run dev --prefix server',
            port:    3000,
            reuseExistingServer: !process.env.CI,
            // A3: 120 s allows cold ts-node + MongoDB connection on CI
            timeout: 120000,
        },
        {
            command: 'npm run dev --prefix client',
            port:    5173,
            reuseExistingServer: !process.env.CI,
            timeout: 120000,
        },
    ],
});
