/**
 * extract-errors.cjs
 *
 * Reads e2e-errors.json (generated by Playwright's JSON reporter)
 * and prints only the FAILED tests with their error messages.
 *
 * Usage:  node e2e/extract-errors.cjs
 * Output: Copy-paste-ready error blocks
 */

const fs = require('fs');
const path = require('path');

const reportPath = path.resolve(__dirname, '..', 'e2e-errors.json');

if (!fs.existsSync(reportPath)) {
    console.error('❌  e2e-errors.json not found. Run `npx playwright test` first.');
    process.exit(1);
}

const report = JSON.parse(fs.readFileSync(reportPath, 'utf-8'));

const failures = [];

for (const suite of report.suites || []) {
    collectFailures(suite, []);
}

function collectFailures(suite, ancestors) {
    const currentPath = [...ancestors, suite.title].filter(Boolean);
    for (const spec of suite.specs || []) {
        for (const test of spec.tests || []) {
            for (const result of test.results || []) {
                if (result.status === 'failed' || result.status === 'timedOut') {
                    failures.push({
                        test:    [...currentPath, spec.title].join(' › '),
                        project: test.projectName || '—',
                        status:  result.status,
                        error:   (result.error?.message || '').split('\n').slice(0, 15).join('\n'),
                        file:    suite.file || spec.file || '—',
                        line:    spec.line || '—',
                        duration: `${Math.round((result.duration || 0) / 1000)}s`,
                    });
                }
            }
        }
    }
    for (const child of suite.suites || []) {
        collectFailures(child, currentPath);
    }
}

if (failures.length === 0) {
    console.log('✅  All tests passed — no failures found.');
    process.exit(0);
}

console.log(`\n❌  ${failures.length} FAILED TEST(S)\n`);
console.log('='.repeat(80));

for (let i = 0; i < failures.length; i++) {
    const f = failures[i];
    console.log(`\n[${i + 1}/${failures.length}] ${f.test}`);
    console.log(`    File:     ${f.file}:${f.line}`);
    console.log(`    Project:  ${f.project}`);
    console.log(`    Status:   ${f.status}  (${f.duration})`);
    console.log(`    Error:`);
    console.log(f.error.split('\n').map(l => `      ${l}`).join('\n'));
    console.log('-'.repeat(80));
}

console.log(`\nTotal: ${failures.length} failure(s)\n`);
